# Generated by Django 3.2.4 on 2022-03-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('customer_photo', models.CharField(max_length=50)),
                ('customer_recording', models.CharField(max_length=50)),
                ('customer_signature', models.CharField(max_length=50)),
                ('customer_fingerprint', models.CharField(max_length=50)),
                ('enrollment_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomersWithFiles',
            fields=[
                ('customer_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('customer_photo', models.FileField(upload_to='')),
                ('customer_recording', models.FileField(upload_to='')),
                ('customer_signature', models.FileField(upload_to='')),
                ('customer_fingerprint', models.FileField(upload_to='')),
                ('enrollment_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
